services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\RedisSessionManager:
        public: true
        autowire: true
        arguments:
            $redisHost: '%env(REDIS_HOST)%'
            $redisPort: '%env(REDIS_PORT)%'

    App\EventSubscriber\JWTRedisSubscriber:
        arguments:
            $redisSessionManager: '@App\Service\RedisSessionManager'
        tags:
            - { name: kernel.event_subscriber }
