name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, zip, sqlite3
        tools: composer
    
    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist --no-progress
    
    - name: Prepare .env.test (SQLite DB)
      run: |
        echo "APP_ENV=test" > .env.test
        echo "APP_SECRET=test" >> .env.test
        echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/test.db" >> .env.test
        echo "JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem" >> .env.test
        echo "JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem" >> .env.test
        echo "JWT_PASSPHRASE=test_passphrase" >> .env.test

    - name: Generate JWT keys
      run: |
        mkdir -p config/jwt
        openssl genpkey -out config/jwt/private.pem -algorithm RSA -pkeyopt rsa_keygen_bits:4096
        openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout

    - name: Prepare test DB
      run: |
        mkdir -p var
        php bin/console cache:clear --env=test --no-warmup
        php bin/console doctrine:schema:create --env=test

    - name: Run PHPUnit tests
      env:
        SYMFONY_DEPRECATIONS_HELPER: disabled
      run: php bin/phpunit --no-coverage
